
name: Build and run Maestro tests upon push/pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: macos-latest
    outputs:
      app: android/app/build/outputs/apk/release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - run: .maestro/test_Android.sh