
name: Build and run Maestro tests upon push/pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: macos-latest
    outputs:
      app: android/app/build/outputs/apk/release
    steps:
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MOBILE_TEST_ENG_TAKE_HOME }}
          app-file: ./android/app/build/outputs/apk/release/app-release.apk
      - run: .maestro/test_Android.sh